spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/damiang19/scrapper-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  application:
    name: "configserver"
  profiles:
    active: git

server:
  port: 8071
