spring:
  profiles:
      active: dev
  application:
    name: pricetracker
  config:
    import: "${SPRING_CONFIG_IMPORT}"
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
server.error.include-message: always
logging.level.org.hibernate.SQL: DEBUG
