spring:
  profiles:
      active: dev
  application:
    name: pricetracker
  config:
    import: "${SPRING_CONFIG_IMPORT}"
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  application:
    name: "price-tracker"
    description: "Application which store scrapped data"
    version: "0.0.1-ALPHA"

server.error.include-message: always
logging.level.org.hibernate.SQL: DEBUG
