spring:
  profiles:
    active: dev
  application:
    name: scrapper
  config:
    import: "${SPRING_CONFIG_IMPORT}"
server:
  port: 8090
  error:
    include-message: always
logging.level.root: INFO
