spring:
  application:
    name: gatewayserver
  config:
    import: "${SPRING_CONFIG_IMPORT}"
  data:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}"
management:
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8072
info:
  application:
    name: "gateway-server"
    description: "Gateway server - edge server"
    version: "0.0.1-ALPHA"
logging:
  level:
    pl.dgorecki.gatewayserver: DEBUG
resilience4j.circuitbreaker:
  slidingWindowSize: 10  # sprawdz 10 requestow. Na podstawie powodzenia ustaw odpowiedni stan
  permittedNumberOfCallsInHalfOpenState: 2 # ilosc requestow wykonanych w stanie half_open
  failureRateThreshold: 50 # ile procent requestow musi zakonczyc sie niepowodzeniem aby stan zostal ustawiony na otwarty
  waitDurationInOpenState: 10000 # jak dlugo ma pozostac w open state